### ISSUE TITLE
Método String.trim não encontrado Elixir 1.2.6

### ISSUE THREAD

**Issue by ecarrara** [pufe/code_brawl#1]
Há trechos no arquivo de boiler plate que usa o método trim_trailing mas a versão do Elixir 1.2.6 que estamos usando não tem esse método.

Mudei para String.strip e aparentemente funcionou!

**Comment by pufe** [comment]
won't fix:
- A plataforma alvo é o elixir 1.3.1 e esse método foi renomeado.
